### PR TITLE
DEV-1172: WIP: aria-expanded="false" for default-collapsed accordions

### PR DESCRIPTION
**Pull request by aelkiss**
Addresses #4 / Deque issue 1727272

I don't have any full-text search index locally so I can't immediately reproduce this, but I wanted to get some WIP up and test further.

### CODE REVIEW

**Comment by aelkiss** [comment]
@moseshll we should coordinate on using this branch for ls in dev perhaps to test further?

**Comment by aelkiss** [comment]
It looks like this template (`build-accordion-item`) gets called here in ways that currently result in the missing `aria-expanded` attribute:

https://github.com/hathitrust/ls/blob/main/web/firebird/list_search_results.xsl#L566
https://github.com/hathitrust/mb/blob/main/web/firebird/list_items.xsl#L235

also for share & transfer collection, which is duplicated across mb and ls
other uses of the template set `<xsl:with-param name="open" select="true()" />`

I'm not sure if we need to add an explicit `<xsl:with-param name="open">false</xsl:with-param>`  or something like that in those other places to get this to work or not.

**Comment by aelkiss** [comment]
Pageturner doesn't appear to use this template; rather it's included in a svelte component in pageturner here https://github.com/hathitrust/pt/blob/master/web/firebird/src/js/components/Panel/index.svelte

Maybe a naïve question, but would it make sense to extract the accordion template from `skeleton.xsl` at some point and make it a component?

**Comment by carylwyatt** [comment]
> Maybe a naïve question, but would it make sense to extract the accordion template from `skeleton.xsl` at some point and make it a component?

Definitely not a naive question! PageTurner is a svelte app, so it's easy to drop svelte components in wherever and just use them. We _could_ use the panel component (and other design components) in the other mdp-web apps, but it would take some set up in firebird in order to both export the component and then tell those apps it should be looking for that component. I did it recently with the cookie consent banner, so I know what to look for, but I'm not sure it's worth it.

**Comment by aelkiss** [comment]
I have verified this is working for https://dev-1.babel.hathitrust.org/mb, but it doesn't seem to be working for ls there. I'm not sure why, but I'll continue investigating that.

**Comment by carylwyatt** [comment]
> It looks like this template (`build-accordion-item`) gets called here in ways that currently result in the missing `aria-expanded` attribute:
> 
> https://github.com/hathitrust/ls/blob/main/web/firebird/list_search_results.xsl#L566 https://github.com/hathitrust/mb/blob/main/web/firebird/list_items.xsl#L235
> 
> also for share & transfer collection, which is duplicated across mb and ls other uses of the template set `<xsl:with-param name="open" select="true()" />`
> 
> I'm not sure if we need to add an explicit `<xsl:with-param name="open">false</xsl:with-param>` or something like that in those other places to get this to work or not.

Thanks for catching those! I'm still not great at reading all the xsl tags, it's like a weird maze to me.

**Comment by carylwyatt** [comment]
> I have verified this is working for https://dev-1.babel.hathitrust.org/mb, but it doesn't seem to be working for ls there. I'm not sure why, but I'll continue investigating that.

It seems to be working in `ls` now! Screen reader told me all the sections were either expanded/collapsed. 👍

**Comment by aelkiss** [comment]
OK, I was able to get it working with ls on dev-1 -- the issue was that it wasn't using the correct mdp-web because I didn't have local.conf set up because I had removed what *had* been there for dev-1 and checked out a fresh copy of ls... Using the `debug=xsl` flag (after getting wayf/ping working) was useful for determining that was what was going on.

**Comment by aelkiss** [comment]
Just to summarize:

`aria-expanded=false` is now present at load for the facets at:

https://dev-1.babel.hathitrust.org/cgi/ls?a=srchls;c=293249306;q1=*
https://dev-1.babel.hathitrust.org/cgi/mb?a=listis;c=464226859
https://dev-1.babel.hathitrust.org/cgi/ls?q1=aardvark&field1=ocr&a=srchls&ft=ft&lmt=ft

So I don't think we need to make any changes in mb/ls for this to work (apart from updating the submodule)

**Review by carylwyatt — APPROVED** [review]
I tested this with a screen reader on dev-1 for both `ls` and `mb` and all the accordions (current filters, item viewability, additional facets, and collection tools in mb) were announced as "expanded" or "collapsed."

**Comment by aelkiss** [comment]
I will go ahead and update the submodule for mb and ls, and get that staged on test.babel.

**Pull request merged**
